import React from 'react';
import { 
  Home, 
  Stethoscope, 
  Video, 
  Calendar, 
  User, 
  ShoppingBag, 
  Menu, 
  Activity, 
  HeartPulse, 
  FileText,
  CreditCard,
  PlusCircle,
  Users,
  Building2,
  Clock,
  ShieldCheck,
  Sparkles,
  Zap,
  Percent,
  Search,
  Star,
  MapPin,
  Calculator,
  Baby,
  Smile,
  Award,
  TrendingUp,
  Tag,
  X,
  Flame,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  CheckCircle,
  Info,
  Ambulance,
  Pill,
  Syringe,
  Wallet,
  Crown,
  Bell,
  ShoppingCart,
  ArrowLeft,
  Gem,
  Timer,
  Eye,
  Type,
  Sun,
  Gift,
  Globe,
  Grid,
  MessageSquare,
  Loader2,
  CalendarDays,
  Mail,
  Smartphone,
  Cpu,
  LogOut,
  Edit,
  Headphones,
  Camera,
  Settings,
  Copy,
  Share2,
  Ticket,
  History,
  RefreshCw,
  ShoppingBasket,
  FileCheck,
  XCircle,
  CheckSquare,
  QrCode,
  Coffee,
  List,
  EyeOff,
  Check,
  ThumbsUp,
  Phone,
  UserX,
  MessageCircle,
  Mic,
  ArrowRight,
  Bone,
  AlertTriangle,
  Dumbbell,
  Scissors,
  Filter,
  Sliders
} from 'lucide-react';

export const LogoIcon = () => (
  <div className="w-24 h-24 rounded-3xl flex items-center justify-center shadow-lg bg-[#0C5A5D]">
    <div className="w-full h-full p-1">
      <svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg" className="w-full h-full">
        {/* Outer Ring */}
        <circle cx="50" cy="50" r="42" stroke="white" strokeWidth="4" />
        
        {/* Pulse Line */}
        <path d="M15 50 H25 L35 30 L50 70 L65 35 L75 50 H80" stroke="white" strokeWidth="5" strokeLinecap="round" strokeLinejoin="round" />
        {/* Dot at the end of pulse */}
        <circle cx="82" cy="50" r="5" fill="white" />
        
        {/* Text */}
        <text x="50" y="85" textAnchor="middle" fill="white" fontFamily="Cairo" fontWeight="800" fontSize="20">إيفر</text>
      </svg>
    </div>
  </div>
);

export const Icons = {
  Home,
  Stethoscope,
  Video,
  Calendar,
  User,
  ShoppingBag,
  Menu,
  Activity,
  HeartPulse,
  FileText,
  CreditCard,
  PlusCircle,
  Users,
  Building2,
  Clock,
  ShieldCheck,
  Sparkles,
  Zap,
  Percent,
  Search,
  Star,
  MapPin,
  Calculator,
  Baby,
  Smile,
  Award,
  TrendingUp,
  Tag,
  X,
  Flame,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  CheckCircle,
  Info,
  Ambulance,
  Pill,
  Syringe,
  Wallet,
  Crown,
  Bell,
  ShoppingCart,
  ArrowLeft,
  Gem,
  Timer,
  Eye,
  Type,
  Sun,
  Gift,
  Globe,
  Grid,
  MessageSquare,
  Loader2,
  CalendarDays,
  Mail,
  Smartphone,
  Cpu,
  LogOut,
  Edit,
  Headphones,
  Camera,
  Settings,
  Copy,
  Share2,
  Ticket,
  History,
  RefreshCw,
  ShoppingBasket,
  FileCheck,
  XCircle,
  CheckSquare,
  QrCode,
  Coffee,
  List,
  EyeOff,
  Check,
  ThumbsUp,
  Phone,
  UserX,
  MessageCircle,
  Mic,
  ArrowRight,
  Bone,
  AlertTriangle,
  Dumbbell,
  Scissors,
  Filter,
  Sliders
};